### ISSUE TITLE
YasGUI Map Plugin

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural-yasgui-plugins#2]
@SteinerPascal I was wondering if you already had something related to display of a SPARQL results on a map ? Do you have a separate repository for this maybe ?

**Comment by tfrancart** [comment]
See https://github.com/SteinerPascal/plant-twin/tree/master/src/sparnaturalmanager/yasgui/plugins/map-plugin

**Comment by tfrancart** [comment]
Idea : not only be able to plot points, but associate them with a metric to drive e.g. circle size or color

**Comment by tfrancart** [comment]
Warning : need to deal with results that do not have a known position. Display a separate list below the map ?

**Comment by tfrancart** [comment]
@antoine37120

**Comment by tfrancart** [comment]
- Sera développé comme un plugin YasGUI, et apparaitra comme un onglet supplémentaire à côté de l'onglet "Table"
- Si on détecte que certaines entités n'ont pas de positions et ne peuvent pas être affichées sur la carte, un message de warning le préviendra et permettra de rebasculer sur l'onglet "Table"
- Le plugin sera capable d'afficher 2 structures de tableaux de résultat : le cas où une colonne contient un datatype wktLiteral, et le cas où on a 2 colonnes contenant une latitude et une longitude (l'algorithme exact de détection de ce cas sera à spécifier, on peut se baser sur les noms des colonnes, et/ou sur l'analyse des valeurs des colonnes)
- Le plugin pourra afficher des points, des lignes ou des polygones
- Une infobulle sur chaque résultat permettra d'afficher les valeurs des différentes colonnes du tableau
- On étudiera la possibilité d'afficher sur la carte de résultat la/les zone(s) de sélection faites dans Sparnatural - cette/ces zones seront affichées dans une couleur différente
- Une configuration JSON permettra de configurer le plugin, par exemple pour les couleurs des marqueurs sur la carte.

**Comment by antoine37120** [comment]
@tfrancart  Voici un premier aperçu avec polygones, centrage auto, et exemple de message. (poussé sur la branche issue-2)

Par contre je ne peux pas tester le fait que des résultats soient sans donnée géo.
Tu pourras voir dans la fonction canHandleResults comment est réalisé la vérification. C'est un comptage. La condition d'affichage du message est dans la fonction createMap.

<img width="1252" alt="image" src="https://github.com/sparna-git/Sparnatural-yasgui-plugins/assets/464395/8cf71cd6-c2a9-42a8-bdcb-fc6f470957ed">

**Comment by tfrancart** [comment]
Merci ! Dans le message il faudrait pouvoir mettre un lien pour rebasculer sur l'onglet "Table". 
Voilà une requête qui ramène quelques entrées sans coordonnées pour tester:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?commune ?nom ?coord
WHERE {
  {
  ?commune wdt:P31 wd:Q484170 .
  ?commune wdt:P131 wd:Q12556 .
  ?commune wdt:P625 ?coord .
  ?commune rdfs:label ?nom . FILTER(lang(?nom) = "fr" && STRSTARTS(STR(?nom), "A"))
  }
  UNION
  {
      ?commune wdt:P31 wd:Q484170 .
      FILTER NOT EXISTS { ?commune wdt:P625 ?coord . }
  }
} LIMIT 50
```

**Comment by antoine37120** [comment]
@thomas Push sur la branche issue-2. Tu peux tester l'affichage des polygones de la recherche. Il y a juste à cliquer sur le bouton de lancement de la requête.

**Comment by tfrancart** [comment]
Merci. Top pour l'affichage des critères de recherche en pointillés.
Je voudrai tester pour voir comment s'affiche les éventuels polygones dans un résultat de recherche.

- Est-ce que ça marche bien avec le plugin Geoman de clustering ?
- est-ce qu'on a aussi les bulles d'infos ?
- il faudrait localiser en français/anglais le message:

![image](https://github.com/sparna-git/Sparnatural-yasgui-plugins/assets/2728945/066a1a9f-4ef1-4b3b-9eca-095f51f95f8c)

- dans ce message, il faudrait mettre un lien pour basculer sur l'onglet Table

J'ai mergé sur main.
