### ISSUE TITLE
Map display : quand il y a la zone cherchée, les infos bulles ne s'affichent plus

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural-yasgui-plugins#6]
Quand il y a la zone cherchée sur la carte d'affichage des résultats, les infobulles ne s'affichent pas.
Quand on fait une recherche sans critère géographique, et qu'il n'y a pas de zone cherché à afficher, les infobulles s'affichent.

**Comment by antoine37120** [comment]
@tfrancart C'est corrigé assez simplement avec l'utilisation d'une fonction native de Leaflet pour positionner les polygones directement en arrière plan : `poly.addTo(this.map).bringToBack();`
